### ISSUE TITLE
股票交易中数据板块分离，进一步可以实现所有板块独立分离窗口

### ISSUE THREAD

**Issue by jayce1212** [moyuanz/DevilYuan#11]
## 股票交易
![image](https://user-images.githubusercontent.com/44791674/53538481-c3318f80-3b48-11e9-952c-a4e19cf312f6.png)
## 数据窗口
![image](https://user-images.githubusercontent.com/44791674/53538530-068bfe00-3b49-11e9-87c9-7501e9ced8bc.png)

**Comment by moyuanz** [comment]
supported, you can right click '数据'->克隆
![image](https://user-images.githubusercontent.com/37684059/53567815-4da2df00-3b9b-11e9-976c-ffe9d491754d.png)
