### ISSUE TITLE
求函数DyStockDataFocusAnalysisUtility

### ISSUE THREAD

**Issue by buyeey** [moyuanz/DevilYuan#14]
File "D:\DevilYuan-master\Stock\Data\Viewer\DyStockDataWindow.py", line 543, in plotReqFocusAnalysis
    focusStrengthDf, focusInfoPoolDict = DyStockDataFocusAnalysisUtility.analysis(dfs, indexDf.index, self._daysEngine.stockCodes, self._eventEngine, self._info)
NameError: name 'DyStockDataFocusAnalysisUtility' is not defined

**Comment by moyuanz** [comment]
fix
