### ISSUE TITLE
在更新股票数据的时候，数据来源来自tushare时候会出现以下问题。

### ISSUE THREAD

**Issue by wangpenghehe** [moyuanz/DevilYuan#3]
![image](https://user-images.githubusercontent.com/1255496/41349645-1d0848aa-6f43-11e8-8404-1156d05f092c.png)

目前我碰到的问题还都集中在拿到数据这一步，量化分析还没到这一步。

**Comment by moyuanz** [comment]
这个是已知问题，估计tushare可能改了接口。我会尽快解决这个问题。解决问题之前，可以用万得的接口。

**Comment by moyuanz** [comment]
bug fix, 但是由于新浪反扒，日线数据用tushare更新会很慢。

**Comment by wangpenghehe** [comment]
这么晚辛苦了。我通过使用wind接口已经更新完成了数据，目前是在做量化选股的时候，会提示说数据库里往前多少天的没有记录，但我再次去更新，提示数据已经最新。
