### ISSUE TITLE
使用了万得接口以后，会反复出现更新历史数据的问题，和量化无结果的问题。

### ISSUE THREAD

**Issue by wangpenghehe** [moyuanz/DevilYuan#4]
如上所述，目前更新数据进度条是正常走的，我在mangodb里看也有相应的collection,里面数据也有但在执行量化选股的时候，一直是没有结果的。
截图如下：
1.更新数据时候的截图
![111](https://user-images.githubusercontent.com/1255496/41444763-b4e179aa-7077-11e8-9bde-ce4777736453.jpg)

![default](https://user-images.githubusercontent.com/1255496/41444906-8a42840e-7078-11e8-99bc-7c2a4631e84d.jpg)

2.量化的结果

![_20180615000948](https://user-images.githubusercontent.com/1255496/41444848-3ac40f88-7078-11e8-849d-bab5614dd608.png)

在命令行里没有exception抛出来。

不知道是否有微信，QQ等工具？可以即时沟通。

**Comment by moyuanz** [comment]
如果每次有新数据，都会更新。量化结果，我看不到

**Comment by wangpenghehe** [comment]
刷新一下页面是否可以？我这里看截图是正常的，在量化的时候会跑进度条，但无论选什么策略，结果是空的。另外还会提示数据库里没有向前多少个交易日的数据，但数据明显是有的。

**Comment by moyuanz** [comment]
主页上有qq群

**Comment by moyuanz** [comment]
缺少交易日数据

**Comment by wangpenghehe** [comment]
数据有的，加载正常，跑完任何策略都没有结果，是确实没有结果还是bug有点讲不清楚了。需要log么？比如我今天选平台向上突破，然后点选服，执行完就是空的

**Comment by moyuanz** [comment]
空，有点就没有选出股票啊。基准日期要填对了

**Comment by moyuanz** [comment]
换个策略试试
